#!/usr/bin/bash

# psql -h m6-image-gallery.ceza2uidpxb7.us-east-1.rds.amazonaws.com -U image_gallery << EOF

${IG_PASSWD} psql -h ${PG_HOST} -U ${IG_USER} <<EOF
create table users (username varchar(100) not null primary key, password varchar(100), full_name varchar(200));

insert into users values ('fred', 'foo', 'Fred Flintstone');
insert into users values ('barney', 'blah', 'Barney Rubble');
insert into users values ('wilma', 'bedrock', 'Wilma Flintstone');
insert into users values ('dongji', 'Dongji', 'cpsc4973');

create table photos (username varchar(100), photoname varchar(200));

insert into photos values ('wilma', 'wilma_photo1');
insert into photos values ('wilma', 'wilma_photo2');
insert into photos values ('wilma', 'wilma_photo3');
insert into photos values ('dongji', 'dongji_photo1');
insert into photos values ('dongji', 'dongji_photo2');
insert into photos values ('dongji', 'dongji_photo3');
insert into photos values ('barney', 'barney_photo1');

EOF

